[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
    'pallets/primitives',
    'pallets/parachain-staking',
    'pallets/pallet-inflation',
    'pallets/crowdloan-reward',
]
