[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    # 'pallets/env',
    # 'pallets/exchange-rate',
    # 'pallets/lockdrop',
    'pallets/roaming/roaming-operators',
    'pallets/roaming/roaming-networks',
    'pallets/roaming/roaming-organizations',
    'pallets/roaming/roaming-network-servers',
    'pallets/roaming/roaming-devices',
    'pallets/roaming/roaming-routing-profiles',
    'pallets/roaming/roaming-service-profiles',
    'pallets/roaming/roaming-accounting-policies',
    'pallets/roaming/roaming-agreement-policies',
    'pallets/roaming/roaming-network-profiles',
    'pallets/roaming/roaming-device-profiles',
    'pallets/roaming/roaming-sessions',
    'pallets/roaming/roaming-billing-policies',
    'pallets/roaming/roaming-charging-policies',
    'pallets/roaming/roaming-packet-bundles',
    'pallets/membership/supernodes',
    'pallets/mining/setting/token',
    'pallets/mining/setting/hardware',
    'pallets/mining/rates/token',
    'pallets/mining/rates/hardware',
    'pallets/mining/sampling/token',
    'pallets/mining/sampling/hardware',
    'pallets/mining/eligibility/token',
    'pallets/mining/eligibility/hardware',
    'pallets/mining/eligibility/proxy',
    'pallets/mining/execution/token',
    'pallets/mining/lodgements/hardware',
    'pallets/mining/claims/token',
    'pallets/mining/claims/hardware',
    'pallets/primitives',
    'pallets/treasury/dao',
    'runtime',
]
