name: Create linux release

on:
  push:
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-03-24
          target: wasm32-unknown-unknown
          override: true

      - name: Build and zip
        run: |
          cargo build --release
          cp ./target/release/datahighway-collator .
          gzip datahighway-collator

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Datahighway-${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: generate raw kusama chainspec
        run: |
          ./target/release/datahighway-collator build-spec --chain kusama --disable-default-bootnode > plain-parachain-chainspec.json
          ./target/release/datahighway-collator build-spec --chain plain-parachain-chainspec.json --disable-default-bootnode --raw > kusama-parachain-raw.json
          
      - name: generate raw rococo chainspec
        run: ./target/release/datahighway-collator build-spec --chain rococo --disable-default-bootnode > rococo-parachain-chainspec.json

      - name: fetch kusama chainspec
        run: wget https://github.com/DataHighway-DHX/DataHighway-Parachain/releases/download/v3.7.1/kusama.json
      
      - name: fetch rococo chainspec
        run: wget https://raw.githubusercontent.com/DataHighway-DHX/DataHighway-Parachain/2c7ee5ddffffee8a7f8867694e791647e38a8fa1/res/rococo/rococo.json

      - name: fetch tanganika chainspec
        run: wget https://raw.githubusercontent.com/DataHighway-DHX/DataHighway-Parachain/v3.6.0/res/kusama/kusama-parachain-raw.json -O ./tanganika-parachain-raw.json

      - name: fetch spreehafen chainspec
        run: wget https://raw.githubusercontent.com/DataHighway-DHX/DataHighway-Parachain/2c7ee5ddffffee8a7f8867694e791647e38a8fa1/res/rococo/rococo-parachain-raw.json -O ./spreehafen-parachain-raw.json

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: datahighway-collator.gz
          asset_name: datahighway-collator.gz
          asset_content_type: application/gzip
      
      - name: upload compressed runtime wasm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/wbuild/datahighway-parachain-runtime/datahighway_parachain_runtime.compact.compressed.wasm
          asset_name: datahighway_parachain_runtime.compact.compressed.wasm
          asset_content_type: application/octet-stream
      
      - name: upload kusama relay chainspec
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kusama.json
          asset_name: kusama.json
          asset_content_type: application/json

      - name: upload rococo relay chainspec
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rococo.json
          asset_name: rococo.json
          asset_content_type: application/json

      - name: upload kusama parachain spec
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kusama-parachain-raw.json
          asset_name: kusama-parachain-raw.json
          asset_content_type: application/json
      
      - name: upload parachain spec (v3.6.0)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tanganika-parachain-raw.json
          asset_name: tanganika-parachain-raw.json
          asset_content_type: application/json
      
      - name: upload rococo parachain spec
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rococo-parachain-chainspec.json
          asset_name: rococo-parachain-chainspec.json
          asset_content_type: application/json

      - name: upload spreehafen spec
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spreehafen-parachain-raw.json
          asset_name: spreehafen-parachain-raw.json
          asset_content_type: application/json