name: Create linux release

on:
  push:
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-15
          target: wasm32-unknown-unknown
          override: true

      - name: Initialize environment and build
        run: |
          rustup update stable
          rustup toolchain install nightly-2021-12-15
          rustup default nightly-2021-12-15
          rustup target add wasm32-unknown-unknown --toolchain nightly-2021-12-15
          rustup override set nightly-2021-12-15
          cargo build --release
          cp ./target/release/datahighway-collator .
          gzip datahighway-collator

      - name: get version
        run: echo "::set-output name=version::$(./target/release/datahighway-collator --version)"
        id: version

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: datahighway-collator.gz
          asset_name: datahighway-collator-amd64.gz
          asset_content_type: application/gzip