name: Create linux release

on:
  push:
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-15
          target: wasm32-unknown-unknown
          override: true

      - name: Initialize environment and build
        run: |
          rustup update stable
          rustup toolchain install nightly-2021-12-15
          rustup default nightly-2021-12-15
          rustup target add wasm32-unknown-unknown --toolchain nightly-2021-12-15
          rustup override set nightly-2021-12-15
          cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: datahighway
          path: target/release/datahighway
