name: Test

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Initialize WASM build environment
        run: |
          rustup update stable
          rustup toolchain install nightly-2023-03-24
          rustup default nightly-2023-03-24
          rustup target add wasm32-unknown-unknown --toolchain nightly-2023-03-24

      - name: Install protoc
        run: |
          sudo apt update
          sudo apt-get install protobuf-compiler

      - name: Run cargo check
        run: cargo +nightly-2023-03-24 check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Initialize WASM build environment
        run: |
          rustup update stable
          rustup toolchain install nightly-2023-03-24
          rustup default nightly-2023-03-24
          rustup target add wasm32-unknown-unknown --toolchain nightly-2023-03-24

      - name: Install protoc
        run: |
          sudo apt update
          sudo apt-get install protobuf-compiler

      # Runs integration tests in the runtime/tests folder
      # To run tests in a specific package run
      # `cargo +nightly-2023-03-24 test -p <package name> (i.e. datahighway-runtime)
      - name: Run All Tests
        run: |
          cargo +nightly-2023-03-24 test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install nightly toolchain for rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # nightly-2023-03-24-x86_64-unknown-linux-gnu
      - name: Initialize WASM build environment
        run: |
          rustup update stable
          rustup toolchain install nightly-2023-03-24
          rustup default nightly-2023-03-24
          rustup target add wasm32-unknown-unknown --toolchain nightly-2023-03-24

      # Ignore use of Rust Linting since rearranging makes it challenging to update to latest Substrate
      # - name: Run cargo fmt
      # run: |
      #   rustup component add rustfmt --toolchain nightly-2023-03-24-x86_64-unknown-linux-gnu
      #   cargo +nightly-2023-03-24 fmt --all -- --check

      # Ignore use of Clippy until a clippy.toml file may be used. See README.md
      # - name: Run cargo clippy
      #   # uses: actions-rs/cargo@v1
      #   # with:
      #   #   command: clippy
      #   #   args:  --release -- -D warnings
      #   # FIXME - temporary fix below. See https://github.com/rust-lang/rust-clippy/issues/5094#issuecomment-579116431
      #   run: |
      #     rustup component add clippy --toolchain nightly-2023-03-24-x86_64-unknown-linux-gnu
      #     rustup component add clippy-preview --toolchain nightly-2023-03-24-x86_64-unknown-linux-gnu
      #     cargo +nightly-2023-03-24 clippy-preview -Zunstable-options
